language: cpp
compiler: gcc
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - libbz2-dev
      - libblas-dev
      - liblapack-dev
      - libarpack2-dev
      - libnetcdf-dev
      - netcdf-bin
      - clang
      - mpich
env:
    - COMPILER=gnu
    - COMPILER=clang
    - COMPILER=gnu BUILD_FLAGS="-openmp" OPT=openmp
    - COMPILER=gnu BUILD_FLAGS="-mpi" DO_PARALLEL="mpiexec -n 2"

install:
    - ./configure $BUILD_FLAGS $COMPILER
    - make -j2 install
      # Hack to get ambpdb installed with OpenMP/MPI
    - make -C src ambpdb && mv src/ambpdb bin/
script:
    - cd test && make test.showerrors
