language: cpp
compiler: gcc
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - libbz2-dev
      - libblas-dev
      - liblapack-dev
      - libarpack2-dev
      - libnetcdf-dev
      - netcdf-bin
env:
    - COMPILER=gnu
    - COMPILER=clang
    - COMPILER=gnu OPENMP="-openmp"

install:
    - ./configure $OPENMP $COMPILER
    - make install
script:
    - cd test && make test
