os: Windows Server 2012

clone_folder: c:\projects\cpptraj

environment:
  matrix:
    - BUILD_TYPE: "cmake-vs"
#    - BUILD_TYPE: "cmake-mingw"
#    - BUILD_TYPE: "configure-mingw"

install:
  - git submodule update --init --recursive
  - devtools\ci\appveyor\setup-environment.bat

build_script:
  - devtools\ci\appveyor\build.bat

after_build:
  - devtools\ci\appveyor\post-build.bat

test_script:
  - set CPPTRAJ_TEST_OS=windows
  - set "PATH=C:/msys64/usr/bin;%ORIG_PATH%;%cd%\bin"
  - echo "PATH for testing-> %PATH%"
  - sh -lc "cd test; make test.showerrors"

artifacts:
  - path: cpptraj-$(APPVEYOR_BUILD_ID).zip
