os: Windows Server 2012

# We need printf exponents to have 2 digits like the C standard says,
# or tests will fail. Set environment variable for mingw-w64:
# https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-crt/stdio/mingw_pformat.c#L223
environment:
  - PRINTF_EXPONENT_DIGITS: "2"
  - matrix:
  #  - USE_CMAKE: "0"
    - USE_CMAKE: "1"

install:
  - devtools\ci\appveyor\setup-environment.bat

build_script:
  - devtools\ci\appveyor\build.bat

after_build:
  - devtools\ci\appveyor\post-build.bat

test_script:
  - set CPPTRAJ_TEST_OS=windows
  - sh -lc "cd test; make test.showerrors"

artifacts:
  - path: cpptraj-$(APPVEYOR_BUILD_ID).zip
